version: "3"

services:

  node:
    image: simplestakingcom/tezedge:latest-release
    command: ["--network=mainnet", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927"]
    hostname: node
    ports:
      - "4927:4927"
      - "19732:9732"
      - "18732:18732"
    networks:
      - default
    tty: true

  explorer:
    image: simplestakingcom/tezedge-explorer:latest-release
    hostname: explorer
    environment:
      - SANDBOX=http://localhost:3030
      # need a better way to provide such information
      - API:[{"id":"localhost","name":"demo.localhost","http":"http://localhost:18732","debugger":"http://localhost:17732","ws":"ws://localhost:4927","monitoring":"http://localhost:38732/resources/tezedge"}]
    ports:
      - "80:80"
      - "8080:80"
    networks:
      - default
    tty: true
