version: "3"

services:

  node:
    image: simplestakingcom/tezedge:latest
    command: ["--network=mainnet", "--p2p-port=9732", "--rpc-port=18732", "--websocket-address=0.0.0.0:4927"]
    hostname: node
    ports:
      - "4927:4927"
      - "19732:9732"
      - "18732:18732"
    networks:
      - default
    tty: true

  explorer:
    image: simplestakingcom/tezedge-explorer:latest
    hostname: explorer
    ports:
      - "8080:8080"
    networks:
      - default
    tty: true