name: rustfmt

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly-2020-12-31
          default: true
      - run: rustup component add rustfmt
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          ## TODO: all modules: https://github.com/simplestaking/tezedge/issues/321
          args: -p ipc -p logging -p fuzz_ack_message -p fuzz_advertise_message -p fuzz_block_header_message -p fuzz_connection_message -p fuzz_current_branch_message -p fuzz_current_head_message -p fuzz_encoding -p fuzz_metadata_message -p fuzz_operation_message -p fuzz_operations_for_blocks_message -p fuzz_peer_response_message -p fuzz_protocol_message -p tezos_api -p tezos_client -p tezos_context -p tezos_encoding -p tezos_identity -p tezos_interop -p tezos_interop_callback -p tezos_messages -p tezos_wrapper -p protocol-runner -p crypto -p shell -p rpc -p monitoring -p sandbox -p light-node -p storage -- --check